cc_library(
    visibility = [
        "//visibility:public",
    ],
    name = "sndfmt",
    srcs = [
        "sndfmt.cc",
    ],
    hdrs = [
        "file_interface.h",
				"file_system_interface.h",
				"sndfmt.h",
    ],
    deps = [
        "@abseil-cpp//absl/log:log",
        "@abseil-cpp//absl/status:status",
    ],
)
